services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-fastapi-app-local
    volumes:
      - ./app:/app/app # app 디렉토리를 컨테이너 /app/app에 마운트 (코드 변경 반영)
      - ./alembic:/app/alembic # alembic 설정/스크립트 마운트
      - ./alembic.ini:/app/alembic.ini # alembic 설정 파일 마운트
      - ./pyproject.toml:/app/pyproject.toml # pyproject.toml 변경 시 확인용
      - ./poetry.lock:/app/poetry.lock # poetry.lock 변경 시 확인용
      - ./tests:/app/tests # 테스트 디렉토리 마운트
    ports:
      - "8000:8000" # 호스트 8000번 포트를 컨테이너 8000번 포트에 연결
    environment:
      - DATABASE_URL=${DATABASE_URL_LOCAL} # 호스트의 .env 파일에서 읽어옴
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_MINUTES=${REFRESH_TOKEN_EXPIRE_MINUTES}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URL=${NAVER_REDIRECT_URL}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_SECRET=${KAKAO_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - SITE_URL=${SITE_URL}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - CLOVA_API_KEY=${CLOVA_API_KEY}
      - CLOVA_API_URL=${CLOVA_API_URL}
      # 개발에 필요한 다른 환경 변수들 추가
      - ENVIRONMENT=local
      - BRN_API_KEY=${BRN_API_KEY}
      - NCP_ACCESS_KEY=${NCP_ACCESS_KEY}
      - NCP_SECRET_KEY=${NCP_SECRET_KEY}
      - NCP_BUCKET_NAME=${NCP_BUCKET_NAME}
      - NCP_ENDPOINT=${NCP_ENDPOINT}
      - NCP_REGION=${NCP_REGION}
    depends_on:
      - db
    # command: supervisord -n -c /etc/supervisor/conf.d/supervisord.conf # 이전 명령어 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # uvicorn 직접 실행 및 리로드 옵션 사용
    # healthcheck 추가 고려 (DB 준비될 때까지 대기)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine # 원하는 PostgreSQL 버전 사용
    container_name: my-postgres-db-local
    volumes:
      - postgres_data:/var/lib/postgresql/data # 데이터 영구 저장을 위한 볼륨
    ports:
      - "5432:5432" # 호스트 5432 포트를 컨테이너 5432 포트에 연결 (DB 툴 연결용)
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # 명명된 볼륨 정의